### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jwdsoft** [andriy-bilynskyy/STM32-AES-Bootloader#1]
Hello
I'm trying to build this project on windows and I get an error
STM32-AES-Bootloader-master>make clean build
rm -f stm/system_stm32f10x.c.o stm/startup_stm32f10x_md.s.o stm/STM32F10x_StdPeriph_Driver/src/misc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.o stm/STM32_USB-FS-Device_Driver/src/usb_core.c.o stm/STM32_USB-FS-Device_Driver/src/usb_init.c.o stm/STM32_USB-FS-Device_Driver/src/usb_int.c.o stm/STM32_USB-FS-Device_Driver/src/usb_mem.c.o stm/STM32_USB-FS-Device_Driver/src/usb_regs.c.o stm/STM32_USB-FS-Device_Driver/src/usb_sil.c.o FreeRTOS-Plus-CLI/FreeRTOS_CLI.c.o tiny-AES-c/aes.c.o hex_parser/hex_parser.c.o src/usb/hw_config.c.o src/usb/usb_conf.c.o src/bl_data.c.o src/cli.c.o src/main.c.o src/stm_hex.c.o keys/iv.bin.o keys/key.bin.o stm/system_stm32f10x.c.d stm/startup_stm32f10x_md.s.d stm/STM32F10x_StdPeriph_Driver/src/misc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.d stm/STM32_USB-FS-Device_Driver/src/usb_core.c.d stm/STM32_USB-FS-Device_Driver/src/usb_init.c.d stm/STM32_USB-FS-Device_Driver/src/usb_int.c.d stm/STM32_USB-FS-Device_Driver/src/usb_mem.c.d stm/STM32_USB-FS-Device_Driver/src/usb_regs.c.d stm/STM32_USB-FS-Device_Driver/src/usb_sil.c.d FreeRTOS-Plus-CLI/FreeRTOS_CLI.c.d tiny-AES-c/aes.c.d hex_parser/hex_parser.c.d src/usb/hw_config.c.d src/usb/usb_conf.c.d src/bl_data.c.d src/cli.c.d src/main.c.d src/stm_hex.c.d keys/iv.bin.d keys/key.bin.d stm32-bl.elf stm32-bl.hex stm32-bl.map
/opt/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc -Wall -std=c99 -fdata-sections -ffunction-sections -mlittle-endian -mthumb -mcpu=cortex-m3 -DSTM32F10X_MD -DHSE_VALUE=8000000u -DUSE_STDPERIPH_DRIVER -g0 -O3 -Icm -Istm -Istm/STM32F10x_StdPeriph_Driver/inc -Istm/STM32_USB-FS-Device_Driver/inc -IFreeRTOS-Plus-CLI -Itiny-AES-c -Ihex_parser -Iconfig -Iconfig/stubs -Isrc/usb -Isrc -MD -c stm/system_stm32f10x.c -o stm/system_stm32f10x.c.o
process_begin: CreateProcess(NULL, /opt/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc -Wall -std=c99 -fdata-sections -ffunction-sections -mlittle-endian -mthumb -mcpu=cortex-m3 -DSTM32F10X_MD -DHSE_VALUE=8000000u -DUSE_STDPERIPH_DRIVER -g0 -O3 -Icm -Istm -Istm/STM32F10x_StdPeriph_Driver/inc -Istm/STM32_USB-FS-Device_Driver/inc -IFreeRTOS-Plus-CLI -Itiny-AES-c -Ihex_parser -Iconfig -Iconfig/stubs -Isrc/usb -Isrc -MD -c stm/system_stm32f10x.c -o stm/system_stm32f10x.c.o, ...) failed.
make (e=2): Le fichier spécifié est introuvable.
make: *** [stm/system_stm32f10x.c.o] Error 2

and I don't know what is the problem and how to solve it

**Comment by andriy-bilynskyy** [comment]
Hi,
It seems you have no compiler installed at path:
TOOLCHAIN_PATH := /opt/gcc-arm-none-eabi-9-2020-q2-update
Try to install compiler at this path or modify path according to your environment.

**Comment by andriy-bilynskyy** [comment]
More detailed:
-Download and install compiler
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
-Check the folder where it's installed.
-In project root Makefile L10: update variable TOOLCHAIN_PATH := with your installed compiler.

Also to flash it or debug you will need openocd which also needs to be installed installation depends on your OS.
You can refer for details to this https://www.youtube.com/watch?v=57-iolU-PpE&t=718s under video exists link to project.

**Comment by jwdsoft** [comment]
thanks
the compiler was installed but not configured in the make file
now after I edited the TOOLCHAIN_PATH variable I got this error
rm -f stm/system_stm32f10x.c.o stm/startup_stm32f10x_md.s.o stm/STM32F10x_StdPeriph_Driver/src/misc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.o stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.o stm/STM32_USB-FS-Device_Driver/src/usb_core.c.o stm/STM32_USB-FS-Device_Driver/src/usb_init.c.o stm/STM32_USB-FS-Device_Driver/src/usb_int.c.o stm/STM32_USB-FS-Device_Driver/src/usb_mem.c.o stm/STM32_USB-FS-Device_Driver/src/usb_regs.c.o stm/STM32_USB-FS-Device_Driver/src/usb_sil.c.o FreeRTOS-Plus-CLI/FreeRTOS_CLI.c.o tiny-AES-c/aes.c.o hex_parser/hex_parser.c.o src/usb/hw_config.c.o src/usb/usb_conf.c.o src/bl_data.c.o src/cli.c.o src/main.c.o src/stm_hex.c.o keys/iv.bin.o keys/key.bin.o stm/system_stm32f10x.c.d stm/startup_stm32f10x_md.s.d stm/STM32F10x_StdPeriph_Driver/src/misc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.d stm/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.d stm/STM32_USB-FS-Device_Driver/src/usb_core.c.d stm/STM32_USB-FS-Device_Driver/src/usb_init.c.d stm/STM32_USB-FS-Device_Driver/src/usb_int.c.d stm/STM32_USB-FS-Device_Driver/src/usb_mem.c.d stm/STM32_USB-FS-Device_Driver/src/usb_regs.c.d stm/STM32_USB-FS-Device_Driver/src/usb_sil.c.d FreeRTOS-Plus-CLI/FreeRTOS_CLI.c.d tiny-AES-c/aes.c.d hex_parser/hex_parser.c.d src/usb/hw_config.c.d src/usb/usb_conf.c.d src/bl_data.c.d src/cli.c.d src/main.c.d src/stm_hex.c.d keys/iv.bin.d keys/key.bin.d stm32-bl.elf stm32-bl.hex stm32-bl.map
"C:/Program Files (x86)/GNU Arm Embedded Toolchain/9 2020-q2-update"/bin/arm-none-eabi-gcc -Wall -std=c99 -fdata-sections -ffunction-sections -mlittle-endian -mthumb -mcpu=cortex-m3 -DSTM32F10X_MD -DHSE_VALUE=8000000u -DUSE_STDPERIPH_DRIVER -g0 -O3 -Icm -Istm -Istm/STM32F10x_StdPeriph_Driver/inc -Istm/STM32_USB-FS-Device_Driver/inc -IFreeRTOS-Plus-CLI -Itiny-AES-c -Ihex_parser -Iconfig -Iconfig/stubs -Isrc/usb -Isrc -MD -c stm/system_stm32f10x.c -o stm/system_stm32f10x.c.o
make: *** [stm/system_stm32f10x.c.o] Error -1073741502

**Comment by andriy-bilynskyy** [comment]
The problem is that you are using Windows. Look now at your compiler:
"C:/Program Files (x86)/GNU Arm Embedded Toolchain/9 2020-q2-update"/bin/arm-none-eabi-gcc
I don't think it's valid path. I think it should be "C:/Program Files (x86)/GNU Arm Embedded Toolchain/9 2020-q2-update/bin/arm-none-eabi-gcc". Also I think the problem with slashes in paths will appear.
In that case you should play with makefile to get correct path.
But I think in case of Windows using Docker with Ubuntu is much more easy.

**Comment by jwdsoft** [comment]
Thank you that is working now
is there a way to use the aes crypter on an already build hex or elf file? I mean make clean build build the project bootloader.what if I already have a bin or hex or elf file already generated and want to encrypt it using the aes crypter.

**Comment by andriy-bilynskyy** [comment]
Anyway you need sources to update project hex file.
That's due to fact that some flash area is already occupied by bootloader.
So after reset bootloader gets control and it starts the application. But default compiled application has reset at the same address that bootloder. So it's due to tat chips no separate bootloader area as for example in AVR MCUs. In that case you should recompile the application with new reset address (cutted FLASH area).
See test_app/stm32_app.ld. This only one difference from your application
FLASH (rx)      : ORIGIN = 0x08004c00, LENGTH = 45K
